version: 2

updates:

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '18:00'
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 25
    labels:
      - dependencies
    versioning-strategy: increase-if-necessary
