# Build
# -------------------------------------

language: node_js
node_js:
    - "5.11"
    - "4.4"
before_script: "npm install -g grunt-cli"

# Deployment
# -------------------------------------

deploy:
    provider: npm
    on:
        tags: true
    email: "lsphillips.mail@gmail.com"
    api_key: "IZ89aqcH3lPZwDjTG+jM/T/kQ94BieKmxk/z6UuBIIQnBiENDmZOGtXVmnAOBGzomC186qfRxdFRotbA714E+r8vwNo1SdJdoa4iiP/7GskmFkYTxnAX6fehRBlushGspj+J9P+kFWUqoqlPE49glvWpNp4uhFs2RxVgQR1zHkTqg1yevchTmvcLlYrcTAWSPigXuFUbpKRFmF6vCCrWNI5Aq0suQtwJ9KycrdMmmJ3zU4kdcmy3fpOv/6SFbA7ThAr2Z64KXcZ/ARAOX8nVsbZ5ptuISjxR9NAspoQoP6eFuy9SMF1E/24hE3NCb2MI+H04BUJkY4xvk2rbYDnhEzDvOuFvvPM2R1iD1sZXAwas0indjcOeNgP0crnQqJVgb6X3CxcD2CjMhBbyaRptGMw8s7elfw+chABRPdMiyZx//O5+hMfIXafEfNxZsBzTrKJL5Xp7Rn/gIRHp77/RSPqrA62sdxrQ3KIMyZ0UGs5wUmjXiDGRi2qOxT7LXWjfF0TOncoo7HTs5W4wVGy7aVO0wuRZLoqQqrtYM9oODOD9Ml/GSW0FX1VGROSYoOosFaiBrc05dM5mcPka0BsNbpdL879K5F11F8eCP0W1mcYvm6Z7pWRa0J7NOYyeb7OBmBaz23QqvxWH5VXfXkwFPUzbR60ri8odTeBydDF3kcs="
