name: Automatically Merge Dependabot Pull Requests

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:

  auto-merge-dependabot-pr:

    name: Automatically Merge Dependabot Pull Requests

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:

      - name: Extract metadata from PR
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: metadata

      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for the PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch') && (steps.metadata.outputs.dependency-type == 'direct:development' || steps.metadata.outputs.dependency-type == 'indirect') }}

    runs-on: ubuntu-latest
